/* Hermes Data-Link — PN15 LFSR Whitening (RFC §3.2)
 *
 * XOR each byte with a pseudorandom sequence generated by a
 * 15-bit LFSR with polynomial x^15 + x^14 + 1.
 * Seed is the lower 15 bits of the sync word.
 * Symmetric: whiten(whiten(data)) == data.
 */
#ifdef ENABLE_HERMES

#include "hermes/hm_whitening.h"

void HERMES_Whiten(uint8_t *data, uint16_t len, uint32_t sync_word) {
    // Seed from lower 16 bits of sync word (must be non-zero) — RFC §2.3
    uint16_t lfsr = (uint16_t)(sync_word & 0xFFFF);
    if (lfsr == 0) lfsr = 0xACE1; // fallback seed

    for (uint16_t i = 0; i < len; i++) {
        uint8_t mask = 0;
        for (uint8_t bit = 0; bit < 8; bit++) {
            mask >>= 1;
            if (lfsr & 1) mask |= 0x80;
            // Feedback: bit0 XOR bit1
            uint16_t feedback = ((lfsr >> 0) ^ (lfsr >> 1)) & 1;
            lfsr = (lfsr >> 1) | (feedback << 14);
        }
        data[i] ^= mask;
    }
}

#endif // ENABLE_HERMES
